### PR TITLE
Added config.url for connecting to a redis URL

### PR DESCRIPTION
**Pull request by apowers313**
Not sure if this is a comprehensive set of URL options, but it's the ones that matter for Heroku and has been tested against Heroku's URL settings.

### CODE REVIEW

**Comment by apowers313** [comment]
@Ryanc1256 Just added a short section to the README.md, let me know what you think

**Comment by Ryanc1256** [comment]
@apowers313 look's good! sweet ill merge them into the current one and see if i can push it out to npm soon :P

**Comment by Ryanc1256** [comment]
woop's pressed the wrong button hehe, should be good now.

**Comment by Ryanc1256** [comment]
@apowers313 there we go! 
it's on NPM too, for you to download :P

**Comment by apowers313** [comment]
@Ryanc1256 awesome, thanks!

**Pull request merged**
