### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by Ryanc1256**
## So, lets start this off!

Need everyone's input!!

here are the current main issues that this PR is going to solve.
#80 #62 #89 #24

Okay this is going to be a mega RP...

So its this PR is just to get the discussion around this started..

So what does this fix?
All the issues above :)

What am I proposing to change and why?
#### _GET_

So first off, we are going to change the way the whole "find" system work's, for the better I think...

So we are going to change the way we handle simple "get" queries the reason why is that the current way is just an awful (for a lack of a better word) way of doing it...
[here](https://github.com/balderdashy/sails-redis/issues/80#issuecomment-154586773) is some of reasoning behind it. 

So to do a simple "model.find( primaryKey )" it has to do multiple "get" requests to get it...
Why not just do "waterline:collectionname:primarykey:value" query? who knows... but what I'm proposing is that we move it to a simple find method...
#### _CREATE_

Now, the next step is going to be changing the "set/create" method, so this method is way to complicated for what it actually does, and it confuses new comers to the project, so cleaning that function up and removing some of the complexity and move them to lower methods or just an ultimate clean up.

We also need to give the users the ability to set the prefix, so instead of defaults to "waterline" you can actually set it, obviously it will continue to default to "waterline" but it would be a nice change for people that want to use it...
#### _Uniqueness_

So at the current state, we manually check if the the value is unique when we do most crud functions, which is fine, but there is a bug around the .save method... so we need to make a better or adapt the current methods...

Now lets try to keep redis consistency...

So we are going to change .find with .get and .find will just map to .get this will keep with redis methodology and the same for create vs .set 

The last and final thing we need TTL, 

So if we add a method called setTTL or something, we can start getting TTL support ( YAY! )

I'm sure I'm missing other thing's but would love everyone's options on this!

I'm just going to keep it here... so please no one merge this one just yet... ill continue to add to it!

### CODE REVIEW

**Comment by Kallikrein** [comment]
I try to focus on atomistic changes to sails-redis instead of overhauling the whole process.

I propose to adress TTL issues first without changing the rest of the behaviour, to keep PR and review easier.

userland expire
---

Using the following custom callback afterCreate(), I can set an expire on my keys :

```javascript
afterCreate: function (createdEntry, cb) {
    var self = this;
    self.native(function (err, connection) {
      console.log('waterline:'+ self.tableName + ':' + self.primaryKey + ':' + createdEntry[self.primaryKey]);
      if (!err)
        connection.expire('waterline:'+ self.tableName + ':' + self.primaryKey + ':' + createdEntry[self.primaryKey], 10);
    });
    cb();
  }
```

Question : 
Is there a better way to access ```'waterline:'+ self.tableName + ':' + self.primaryKey + ':' + createdEntry[self.primaryKey]```

custom primaryKey
---

If I use a model with : 

```javascript
module.exports = {
  autoPK: false,
  attributes: {
    email: {
      type: 'email',
      required: true,
      primaryKey: true
    }
}
```

I can set expire with the previous snippet, but the primary key is also stored in the indexed set : 
index.js line 482

```javascript
addToSet: ['saveKeyData', function(next, results) {

      var index = self.schema.indexKey(name, primary);

      // Grab the key to use for this record
      var noSqlKey = self.schema.recordKey(name, primary, data[primary]);

      self.connection.sadd(index, noSqlKey, function(err) {
        if(err) return next(err);
        next();
      });

    }]
```

Now once the key expires, I can't create a new one with the same primaryKey value, since there is still an entry in ```self.schema.indexKey(name, primary)```
So, I thought of a very simple fix : 
Here, can we set an expire on the index set values too ? That way, if the unique index disappear at the same time as the key I want to expire(), the unique throw would disappear.

Then we could easily do a method setTTL() that would expire the 'main' key and the 'unique index' key in one method.

I notice the addToSet async uses redis.sadd()

I will try today to acess the individual values in the set. I don't know yet if we can expire data inside of a set.

If we can't, we might use another storage pattern that allows it.

**Comment by Kallikrein** [comment]
Ok so it seems we can't set expire on items in a set : 

https://quickleft.com/blog/how-to-create-and-expire-list-items-in-redis/

So maybe we might just use a prefix index namespace to store, request and expire unique keys

**Comment by Kallikrein** [comment]
index.js

```javascript
multi.sismember(idx.keyName, data[idx.name]);
```
sismember checks if an item is part of a set.

**Comment by Kallikrein** [comment]
@particlebanana 

What to you think of keeping the unique checks and storage conceptually, but to store relevant data outside of sets so that we can set expire() on the unique index individual keys as part of a setTTL method ?

**Comment by Kallikrein** [comment]
With a little more detail in the proposition : 

in index.js line 755

```javascript
Database.prototype._uniqueConstraint = function _uniqueConstraint(collectionName, data, cb) {
 // ...
  indices.forEach(function(idx) {
    if(!hasOwnProperty(data, idx.name)) return;
    // --- multi.sismember(idx.keyName, data[idx.name]);
    //+++
    multi.get([idx.keyName, data[idx.name]].join(':'));
  });
// ...
};
```

**Comment by particlebanana** [comment]
@Ryanc1256 sorry it took so long to reply! I think these changes are much needed and for the better. Make it a breaking change - maybe bump it to `1.0.0`.

I want to make sure you have whatever you need to make sails-redis work for you and everyone else who is using it. Going to shoot you an email in a min with some ideas.

@Kallikrein I defer to @Ryanc1256 on structural changes.

**Comment by Ryanc1256** [comment]
Okay, Sorry it's been a while... I'm starting to work on it now... 

So i've already tweaked it to 
#84 so this PR will resolve that...

**Comment by ianko** [comment]
@Ryanc1256 What is missing to get this pull request accepted?

And, one more question, do you believe your master branch is safe to run in production?

Thank you.

**Comment by Ryanc1256** [comment]
@ianko Hey, 

im waiting for them to pull in a pull request on another module (https://github.com/balderdashy/waterline-criteria/pull/28), so i have to wait until that one gets pulled in...

And I would say it's 'safe' as its just at the moment its just has a way faster find method.... but then again i haven't tested everything, so i would also say that it isn't at the same time.

**Pull request merged**
