### PR TITLE
many-to-many relationship.

### PR DESCRIPTION
**Pull request by Ryanc1256**
Just fixed a bug with the many-to-many relationship issue #54

### CODE REVIEW

**Comment by dmarcelino** [comment]
Hi @Ryanc1256, the [travis build](https://travis-ci.org/balderdashy/sails-redis/jobs/63898867#L216) just says "Uncaught Error: ERR invalid DB index" which makes it hard to see if these changes improves (or at least doesn't worsen) the current testing scenario. Meanwhile a few changes (#64, #68 and #70) were made in master to improve the travis build. Can you please merge `master` into your branch to see the results? Thanks

**Comment by Ryanc1256** [comment]
@dmarcelino Hey, yeah just merged them, i do see that error but even if i run the test's without my changes it's still fails with that error plus an extra 44 error's due to assertionErrors.

**Comment by dmarcelino** [comment]
Yes, latest master (https://travis-ci.org/balderdashy/sails-redis/jobs/64293043#L533) breaks with 44 errors.

**Comment by Ryanc1256** [comment]
You think we should fix up some of the find queries to fix up the error's to stop the travis builds from breaking?

**Comment by dmarcelino** [comment]
Most definitely! We need to bring sails-redis up to speed with the other official adapters. In waterline-adapter-tests we run the tests against all official adapters and the current scenario is a bit grim:

```
 ------------------------------------------------------------------ 
| adapter          | version | result | failed | total | wl-sequel |
|------------------|---------|--------|--------|-------|-----------|
| sails-postgresql | 30317cd | passed |      0 |   302 |     0.4.0 |
| sails-memory     | c7b0610 | passed |      0 |   276 |           |
| sails-disk       | e95628b | passed |      0 |   275 |           |
| sails-mongo      | fd788af | passed |      0 |   279 |           |
| sails-mysql      | f1e6393 | passed |      0 |   305 |     0.4.0 |
| sails-redis      | 7db00c1 | failed |     43 |   212 |           |
 ------------------------------------------------------------------- 
```
Build: https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/63842997#L1642

**Comment by Ryanc1256** [comment]
Yeah, agreed it does look pretty grim. Okay ill give it ago and see if i can't get the number lower, since it's all association error's it shouldn't be too hard to fix haha

**Comment by dmarcelino** [comment]
Good luck! :+1:

**Comment by Ryanc1256** [comment]
@dmarcelino Looks like it's something with the criteria[here](https://github.com/balderdashy/sails-redis/blob/master/lib/adapter.js#L193) that get sent back from waterline-cursor or something...

**Comment by dmarcelino** [comment]
Interesting, both `sails-memory` and `sails-disk` (and I believe `sails-mongo`) use `waterline-cursor` so one would expect it to work... I did try updating both `waterline-cursor` and `waterline-criteria` to the latest versions but the build already threw several errors: https://travis-ci.org/dmarcelino/sails-redis/jobs/65004072. I wonder if it's the parameters of `runJoins` that needs some adjusting.

**Comment by Ryanc1256** [comment]
Yeah, I'm still having a look at it trying to get it working properly. So i get this back in one of the first test's 

```javascript 
{ a_customer: 
   { createdAt: '2015-06-02T01:56:16.618Z',
     updatedAt: '2015-06-02T01:56:16.618Z',
     id: 4 },
  amount: 1,
  type: 'belongsTo find',
  createdAt: '2015-06-02T01:56:16.623Z',
  updatedAt: '2015-06-02T01:56:16.623Z',
  id: 3 }
```

and it should be finding a_customer with an id of 3 but for some reason it brings back a query with
```javascript 
{ where: { id: 4 } }
```

but it's weird, it returns this query first before the 4th one...
```javascript 
{ where: { id: 3 } }
```

first but that just get's overwritten for some reason.

**Comment by Ryanc1256** [comment]
haha, figured it out lol, was about to rage quit but totally figured it out, so it was only because someone wasn't taking doing primary keys properly (https://github.com/balderdashy/sails-redis/blob/master/lib/adapter.js#L219)[here]

**Comment by Ryanc1256** [comment]
@dmarcelino Well that work's, except for one query but i think it's more of a bug with the waterline-test-adapter unless im reading the query wrong [here](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/associations/hasMany/find.populate.where.js#L135)

Shouldn't it be the same in both cases? 


ah look's like everything else fails there too... sweet...

**Comment by dmarcelino** [comment]
Oh wow, amazing work @Ryanc1256! That's a substantial improvement in a short period of time.

Regarding the waterline-adapter-tests, that's awkward. I'm looking at the latest waterline-adapter-tests [integration build](https://travis-ci.org/balderdashy/waterline-adapter-tests/jobs/64463898) (just triggered it) and I see all official adapters passing their tests with the exception of sails-redis which makes it hang. So I'm not so sure the test is to blame for. I've also tried running your sails-redis branch against the previous version of waterline-adapter-tests (0.10.11) and it also failed the same test: https://travis-ci.org/dmarcelino/sails-redis/jobs/65057283

I think the test is OK, the key part is the `populate` where clause which filters the populated payments in [find.populate.where.js#L122](https://github.com/balderdashy/waterline-adapter-tests/blob/master/interfaces/associations/hasMany/find.populate.where.js#L122):
```js
          Associations.Customer.find({ name: 'hasMany find where' })
          .populate('payments', {where : { id: payment.id }, sort : {amount : 1}})
```

Os that makes `customers[0].payments.length` differ from `customers[1].payments.length`.

@particlebanana, @tjwebb, @devinivy, take a look at this PR, sails-redis is almost fixed, almost...

**Comment by devinivy** [comment]
Looking really good!  Some day we should clean-up sails-redis and add some comments into the code.  Perhaps it should be a different project for another day, but would love the help of @Ryanc1256, given his familiarity with the codebase!  Thanks so much for all the effort, @Ryanc1256.

**Comment by Ryanc1256** [comment]
@dmarcelino @devinivy Thank's, I use this module quite a bit so thought i might as well fix it up and give it some love and make it more inline with the other db connectors for sails and address some of the other peoples problems. 

And yes we **NEED** to comment it, it was mission trying to figure out what everything was doing haha, but got there in the end, wouldn't mind helping love helping other people with their code problems :smile:.

**Comment by Ryanc1256** [comment]
@devinivy @dmarcelino **woopy!!** so the builds are successful for once now! and no more errors haha.

**Comment by dmarcelino** [comment]
Oh my, these are amazing news! Thank you very much @Ryanc1256! And congratulations for a great job done. :clap: :clap: 

@particlebanana, please take a look at this, sails-redis is finally fixed! :D

**Comment by devinivy** [comment]
Brilliant!  The fixes you added make sense.

**Comment by Ryanc1256** [comment]
@devinivy yeah was just thinking ahead of time.

**Comment by particlebanana** [comment]
Bam! Thanks @Ryanc1256 this is great. I'll get it published to npm. Also because you mentioned you are using sails-redis in a lot of projects I made you a collaborator so you can push out patches and merge PR's when needed!

**Comment by Ryanc1256** [comment]
@particlebanana Awesome! thanks.

**Comment by dmarcelino** [comment]
Awesomeness! :D

**Pull request merged**
